#!/usr/bin/env bash

if [[ -n ${J3W1ZSH_ENV_LOADED:-} ]]; then
  return 0
fi
readonly J3W1ZSH_ENV_LOADED=1

J3W1ZSH_REPO_ROOT="${J3W1ZSH_REPO_ROOT:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../../.." && pwd -P)}"
J3W1ZSH_TEST_MODE="${J3W1ZSH_TEST_MODE:-0}"
if [[ $J3W1ZSH_TEST_MODE == 1 ]]; then
  J3W1ZSH_STATE_DIR="${J3W1ZSH_STATE_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/j3w1zsh}"
  J3W1ZSH_CONFIG_DIR="${J3W1ZSH_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/j3w1zsh}"
  J3W1ZSH_CACHE_DIR="${J3W1ZSH_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/j3w1zsh}"
else
  J3W1ZSH_STATE_DIR="$HOME/.local/state/j3w1zsh"
  J3W1ZSH_CONFIG_DIR="$HOME/.config/j3w1zsh"
  J3W1ZSH_CACHE_DIR="$HOME/.cache/j3w1zsh"
fi
J3W1ZSH_DRY_RUN="${J3W1ZSH_DRY_RUN:-0}"
J3W1ZSH_ASSUME_YES="${J3W1ZSH_ASSUME_YES:-0}"
J3W1ZSH_FORCE="${J3W1ZSH_FORCE:-0}"
J3W1ZSH_OUTPUT_MODE="${J3W1ZSH_OUTPUT_MODE:-human}"
J3W1ZSH_COLOR_MODE="${J3W1ZSH_COLOR_MODE:-auto}"
J3W1ZSH_PRESET="${J3W1ZSH_PRESET:-j3w1}"
J3W1ZSH_THEME="${J3W1ZSH_THEME:-j3w1zsh}"
J3W1ZSH_SELECTED_WORKSPACE="${J3W1ZSH_SELECTED_WORKSPACE:-}"
J3W1ZSH_NO_PACKAGES="${J3W1ZSH_NO_PACKAGES:-0}"
J3W1ZSH_PACKAGES_ONLY="${J3W1ZSH_PACKAGES_ONLY:-0}"

# shellcheck disable=SC1091
source "$J3W1ZSH_REPO_ROOT/versions.env"

# These constants are consumed by separately sourced command modules.
# shellcheck disable=SC2034
readonly J3W1ZSH_STATE_SCHEMA_VERSION=1
# shellcheck disable=SC2034
readonly J3W1ZSH_JSON_SCHEMA_VERSION=1
# shellcheck disable=SC2034
readonly J3W1ZSH_EXIT_FAILURE=1
# shellcheck disable=SC2034
readonly J3W1ZSH_EXIT_USAGE=2
# shellcheck disable=SC2034
readonly J3W1ZSH_EXIT_CHECKPOINT=20
# shellcheck disable=SC2034
readonly J3W1ZSH_EXIT_PROTECTED=21

export J3W1ZSH_REPO_ROOT J3W1ZSH_STATE_DIR J3W1ZSH_CONFIG_DIR J3W1ZSH_CACHE_DIR
export J3W1ZSH_DRY_RUN J3W1ZSH_ASSUME_YES J3W1ZSH_FORCE J3W1ZSH_TEST_MODE
export J3W1ZSH_OUTPUT_MODE J3W1ZSH_COLOR_MODE J3W1ZSH_PRESET J3W1ZSH_THEME
export J3W1ZSH_SELECTED_WORKSPACE J3W1ZSH_NO_PACKAGES J3W1ZSH_PACKAGES_ONLY
