#!/usr/bin/env bash

readonly J3W1ZSH_REPOSITORY_ID=1318126833
readonly J3W1ZSH_CANONICAL_URL='https://github.com/j3w1/j3w1zsh.git'
readonly J3W1ZSH_GENERATED_UPDATE_PATH='dotfiles/nvim/.config/nvim/lazy-lock.json'

j3w1zsh_git_normalize_url() {
  local url="$1"
  case "$url" in
  git@github.com:*) printf 'https://github.com/%s\n' "${url#git@github.com:}" ;;
  *) printf '%s\n' "$url" ;;
  esac | sed 's#/$##'
}

j3w1zsh_git_canonical_url() {
  if [[ $J3W1ZSH_TEST_MODE == 1 && -n ${J3W1ZSH_TEST_CANONICAL_URL:-} ]]; then
    printf '%s\n' "$J3W1ZSH_TEST_CANONICAL_URL"
  else
    printf '%s\n' "$J3W1ZSH_CANONICAL_URL"
  fi
}

j3w1zsh_git_is_url() {
  [[ $(j3w1zsh_git_normalize_url "$1") == "$(j3w1zsh_git_normalize_url "$2")" ]]
}

j3w1zsh_git_relation() {
  local remote_url="$1" remote_ref="$2" remote_oid="$3"
  local local_oid
  local_oid="$(git -C "$J3W1ZSH_REPO_ROOT" rev-parse HEAD)"
  local counts=""
  if git -C "$J3W1ZSH_REPO_ROOT" cat-file -e "$remote_oid^{commit}" 2>/dev/null; then
    counts="$(git -C "$J3W1ZSH_REPO_ROOT" rev-list --left-right --count "$local_oid...$remote_oid")"
  else
    local temporary
    temporary="$(mktemp -d "${TMPDIR:-/tmp}/j3w1zsh-update-relation.XXXXXX")"
    git -C "$temporary" init -q
    git -C "$temporary" remote add candidate "$remote_url"
    git -C "$temporary" fetch -q candidate "$remote_ref:refs/j3w1zsh/remote"
    git -C "$temporary" remote add local "$J3W1ZSH_REPO_ROOT"
    git -C "$temporary" fetch -q local "$local_oid:refs/j3w1zsh/local"
    counts="$(git -C "$temporary" rev-list --left-right --count refs/j3w1zsh/local...refs/j3w1zsh/remote)"
    rm -r -- "$temporary"
  fi
  local ahead behind
  read -r ahead behind <<<"$counts"
  jq -cn --arg local_oid "$local_oid" --arg remote_oid "$remote_oid" \
    --argjson ahead "${ahead:-0}" --argjson behind "${behind:-0}" \
    '{local_oid:$local_oid,remote_oid:$remote_oid,ahead:$ahead,behind:$behind,diverged:($ahead>0 and $behind>0)}'
}

j3w1zsh_git_checkout_status() {
  git -C "$J3W1ZSH_REPO_ROOT" status --short --untracked-files=all
}

j3w1zsh_git_generated_drift_only() {
  local status="$1"
  [[ -n $status ]] || return 1
  git -C "$J3W1ZSH_REPO_ROOT" diff --cached --quiet -- || return 1
  [[ -z $(git -C "$J3W1ZSH_REPO_ROOT" ls-files --others --exclude-standard) ]] || return 1
  local changed
  changed="$(git -C "$J3W1ZSH_REPO_ROOT" diff --name-only --diff-filter=M)"
  [[ $changed == "$J3W1ZSH_GENERATED_UPDATE_PATH" ]]
}

j3w1zsh_git_protected_stop() {
  local status="$1"
  [[ $J3W1ZSH_OUTPUT_MODE == json ]] || printf '%s\n' "$status" >&2
  j3w1zsh_die "Authored, staged, deleted, renamed, or untracked checkout state was preserved for owner review." \
    "$J3W1ZSH_EXIT_PROTECTED" protected_checkout
}

j3w1zsh_git_prepare_checkout() {
  local status
  status="$(j3w1zsh_git_checkout_status)"
  [[ -n $status ]] || return 0
  j3w1zsh_git_generated_drift_only "$status" || j3w1zsh_git_protected_stop "$status"
  if [[ $J3W1ZSH_DRY_RUN == 1 ]]; then
    j3w1zsh_note "Would preserve and repair generated runtime drift: $J3W1ZSH_GENERATED_UPDATE_PATH"
    return 0
  fi
  j3w1zsh_ensure_dirs
  local recovery
  recovery="$J3W1ZSH_STATE_DIR/update-recovery/$(date +%Y%m%d-%H%M%S-%N)"
  mkdir -p "$recovery/files/$(dirname -- "$J3W1ZSH_GENERATED_UPDATE_PATH")"
  chmod 700 "$recovery"
  git -C "$J3W1ZSH_REPO_ROOT" diff --binary -- "$J3W1ZSH_GENERATED_UPDATE_PATH" >"$recovery/generated-drift.patch"
  cp -p -- "$J3W1ZSH_REPO_ROOT/$J3W1ZSH_GENERATED_UPDATE_PATH" "$recovery/files/$J3W1ZSH_GENERATED_UPDATE_PATH"
  chmod 600 "$recovery/generated-drift.patch"
  git -C "$J3W1ZSH_REPO_ROOT" restore --worktree -- "$J3W1ZSH_GENERATED_UPDATE_PATH"
  [[ -z $(j3w1zsh_git_checkout_status) ]] || j3w1zsh_git_protected_stop "$(j3w1zsh_git_checkout_status)"
  j3w1zsh_note "Generated bytes and patch were preserved at: $recovery"
}

j3w1zsh_git_remote_branch_oid() {
  local url="$1" branch="$2"
  git ls-remote "$url" "refs/heads/$branch" | awk 'NR==1 {print $1}'
}

j3w1zsh_git_classify_repository() {
  [[ -d $J3W1ZSH_REPO_ROOT/.git ]] || j3w1zsh_die "Update requires a Git checkout."
  local branch origin_url canonical old_canonical identity tracking_ref tracking_remote tracking_branch tracking_url
  branch="$(git -C "$J3W1ZSH_REPO_ROOT" symbolic-ref --quiet --short HEAD 2>/dev/null || true)"
  [[ -n $branch ]] || j3w1zsh_die "Detached HEAD cannot be updated automatically." "$J3W1ZSH_EXIT_PROTECTED" detached_head
  origin_url="$(git -C "$J3W1ZSH_REPO_ROOT" remote get-url origin 2>/dev/null || true)"
  [[ -n $origin_url ]] || j3w1zsh_die "The origin remote is missing." "$J3W1ZSH_EXIT_PROTECTED" missing_origin
  canonical="$(j3w1zsh_git_canonical_url)"; old_canonical="$(j3w1zsh_legacy_canonical_url)"
  if j3w1zsh_git_is_url "$origin_url" "$canonical"; then identity=canonical
  elif j3w1zsh_git_is_url "$origin_url" "$old_canonical"; then identity=old-canonical
  else identity=fork
  fi
  if ! tracking_ref="$(git -C "$J3W1ZSH_REPO_ROOT" rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' 2>/dev/null)"; then
    tracking_ref=""
  fi
  [[ -n $tracking_ref ]] || j3w1zsh_die "Current branch has no upstream; owner review is required." "$J3W1ZSH_EXIT_PROTECTED" missing_upstream
  tracking_remote="${tracking_ref%%/*}"
  tracking_branch="${tracking_ref#*/}"
  tracking_url="$(git -C "$J3W1ZSH_REPO_ROOT" remote get-url "$tracking_remote")"
  jq -cn --arg branch "$branch" --arg origin_url "$origin_url" --arg identity "$identity" \
    --arg tracking_ref "$tracking_ref" --arg tracking_remote "$tracking_remote" --arg tracking_branch "$tracking_branch" --arg tracking_url "$tracking_url" \
    '{branch:$branch,origin_url:$origin_url,identity:$identity,tracking_ref:$tracking_ref,tracking_remote:$tracking_remote,tracking_branch:$tracking_branch,tracking_url:$tracking_url}'
}

j3w1zsh_git_verify_old_redirect_identity() {
  local old_url="$1" new_url="$2" old_head new_head
  old_head="$(git ls-remote "$old_url" HEAD | awk 'NR==1 {print $1}')"
  new_head="$(git ls-remote "$new_url" HEAD | awk 'NR==1 {print $1}')"
  [[ -n $old_head && $old_head == "$new_head" ]] || j3w1zsh_die "Former and new canonical remotes do not identify the same current repository."
  if [[ $J3W1ZSH_TEST_MODE != 1 ]] && j3w1zsh_have gh && gh auth status >/dev/null 2>&1; then
    local repository_id
    repository_id="$(gh api repos/j3w1/j3w1zsh --jq .id)"
    [[ $repository_id == "$J3W1ZSH_REPOSITORY_ID" ]] || j3w1zsh_die "Canonical repository numeric identity does not match."
  fi
}
